---
services:
  db:
    image: postgres:13
    container_name: synapse_db
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse_user
      POSTGRES_PASSWORD: signal123
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapse_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  synapse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synapse_server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8008:8008"
    volumes:
      - ./synapse_data:/data
    command: >
      sh -c "while ! nc -z db 5432; do sleep 1; done; python -m synapse.app.homeserver --config-path /data/homeserver.yaml"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8008/_matrix/v || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  nginx:
    image: nginx:latest
    container_name: synapse_nginx
    depends_on:
      synapse:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    command: nginx -g 'daemon off;'

volumes:
  postgres_data:
  synapse_data:
